name: Update Profile README

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Profile Repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats (Including Private Repos)
        uses: anuraghazra/github-readme-stats@15.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "kylo-539"
          git config --global user.email "kas.11.20144@gmail.com"
          git add README.md
          git commit -m "Update README with private repo stats"
          git push
